# Generated by scripts/compile_schemas.py
# Do not edit manually — re-run the script to regenerate.

from __future__ import annotations

from animus_types.action import AnimusActionObject
from animus_types.assessment import AnimusAssessmentObject
from animus_types.claim import AnimusClaimObject

# Generated contract models
from animus_types.common import (
    ArtifactType,
    CognitiveRole,
    Common,
    EpistemicStatus,
    Integrity,
    LifecycleStatus,
    Presentation,
    Provenance,
    SecurityClass,
    StorageTier,
    SubjectDomain,
    Tag,
    TransactionTime,
    ValidTime,
    WorkflowStatus,
)
from animus_types.decision import AnimusDecisionObject

# Re-export legacy types (preserved for backward compatibility)
from animus_types.egress import EgressDeniedError, is_egress_allowed
from animus_types.entity import AnimusEntityObject
from animus_types.event import AnimusEventObject
from animus_types.forecast import AnimusForecastObject
from animus_types.hypothesis import AnimusHypothesisObject
from animus_types.lesson import AnimusLessonObject
from animus_types.observation import AnimusObservationObject
from animus_types.outcome import AnimusOutcomeObject
from animus_types.pattern import AnimusPatternObject
from animus_types.sensitivity import Sensitivity
from animus_types.signal import AnimusSignalObject
from animus_types.source import AnimusSourceObject

__all__ = [
    # Legacy
    "EgressDeniedError",
    "is_egress_allowed",
    "Sensitivity",
    # Common
    "Common",
    "SubjectDomain",
    "ArtifactType",
    "CognitiveRole",
    "WorkflowStatus",
    "EpistemicStatus",
    "LifecycleStatus",
    "StorageTier",
    "Presentation",
    "SecurityClass",
    "ValidTime",
    "TransactionTime",
    "Provenance",
    "Integrity",
    "Tag",
    # Schema models
    "AnimusActionObject",
    "AnimusAssessmentObject",
    "AnimusClaimObject",
    "AnimusDecisionObject",
    "AnimusEntityObject",
    "AnimusEventObject",
    "AnimusForecastObject",
    "AnimusHypothesisObject",
    "AnimusLessonObject",
    "AnimusObservationObject",
    "AnimusOutcomeObject",
    "AnimusPatternObject",
    "AnimusSignalObject",
    "AnimusSourceObject",
]
