# Generated by scripts/compile_schemas.py
# Do not edit manually — re-run the script to regenerate.

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, constr

from .common import Common


class RiskClass(Enum):
    R0 = "R0"
    R1 = "R1"
    R2 = "R2"
    R3 = "R3"
    R4 = "R4"


class Status(Enum):
    proposed = "proposed"
    authorized = "authorized"
    executing = "executing"
    succeeded = "succeeded"
    failed = "failed"
    compensated = "compensated"
    denied = "denied"


class Payload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    action_kind: constr(min_length=1)
    risk_class: RiskClass
    target: constr(min_length=1)
    parameters: dict[str, Any]
    approval_required: bool
    approval_id: str | None
    idempotency_key: constr(min_length=8)
    status: Status
    compensation_action_ref: str | None = None


class AnimusActionObject(Common):
    artifact_type: Literal["action"] | None = None
    schema_id: Literal["https://animus.local/schemas/action.schema.json"] | None = None
    payload: Payload | None = None
