# Generated by scripts/compile_schemas.py
# Do not edit manually — re-run the script to regenerate.

from __future__ import annotations


from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, constr


class Status(Enum):
    active = 'active'
    consumed = 'consumed'
    expired = 'expired'
    revoked = 'revoked'


class AnimusApprovalReceipt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    approval_id: constr(pattern=r'^apr-[a-z0-9_-]+$')
    principal_id: constr(min_length=3)
    owner_id: constr(pattern=r'^owner-[a-z0-9_-]+$')
    workspace_id: constr(pattern=r'^ws-[a-z0-9_-]+$')
    purpose: constr(min_length=1)
    resource_refs: list[str]
    action_scope: dict[str, Any]
    issued_at: AwareDatetime
    expires_at: AwareDatetime
    policy_version: constr(min_length=1)
    status: Status
    signature: constr(min_length=16)
