# Generated by scripts/compile_schemas.py
# Do not edit manually — re-run the script to regenerate.

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, confloat, constr

from .common import Common


class ConfidenceDimensions(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    evidence: confloat(ge=0.0, le=1.0)
    reasoning: confloat(ge=0.0, le=1.0)
    prediction: confloat(ge=0.0, le=1.0)
    action: confloat(ge=0.0, le=1.0)


class Severity(Enum):
    low = "low"
    medium = "medium"
    high = "high"
    critical = "critical"


class DissentItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    position: str
    severity: Severity
    agent_ref: str | None = None


class Payload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    question: constr(min_length=1)
    judgment: constr(min_length=1)
    evidence_refs: list[str] = Field(..., min_length=1)
    alternative_judgments: list[str] = Field(..., min_length=1)
    confidence_dimensions: ConfidenceDimensions
    dissent: list[DissentItem]


class AnimusAssessmentObject(Common):
    artifact_type: Literal["assessment"] | None = None
    schema_id: Literal["https://animus.local/schemas/assessment.schema.json"] | None = None
    payload: Payload | None = None
