# Generated by scripts/compile_schemas.py
# Do not edit manually — re-run the script to regenerate.

from __future__ import annotations

from enum import Enum

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    confloat,
    conint,
    constr,
)


class ScopeItem(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class ActionEnum(Enum):
    create = "create"
    read = "read"
    update = "update"
    delete = "delete"
    execute = "execute"
    approve = "approve"
    delegate = "delegate"
    export = "export"
    import_ = "import"


class Budget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    max_calls: conint(ge=1) | None = None
    max_tokens: conint(ge=1) | None = None
    max_cost: confloat(ge=0.0) | None = None
    window_seconds: conint(ge=1) | None = None


class RequireApprovalAboveRisk(Enum):
    low = "low"
    medium = "medium"
    high = "high"
    critical = "critical"


class Conditions(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    require_approval_above_risk: RequireApprovalAboveRisk | None = None
    allowed_workspaces: list[str] | None = None
    allowed_schemas: list[str] | None = None


class CapabilityGrant(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    grant_id: constr(pattern=r"^grant-[a-z0-9_-]+$")
    principal: constr(min_length=3)
    scope: list[ScopeItem] = Field(
        ...,
        description="Permission scopes granted (e.g., read, write, delete, admin)",
        min_length=1,
    )
    resource: constr(min_length=1) = Field(
        ...,
        description="Resource pattern this grant applies to (e.g., workspace, object_id glob)",
    )
    action: list[ActionEnum] = Field(..., min_length=1)
    granted_by: constr(min_length=3)
    granted_at: AwareDatetime
    expires_at: AwareDatetime | None = None
    budget: Budget | None = None
    conditions: Conditions | None = None
    revoked_at: AwareDatetime | None = None
    revoked_by: str | None = None
    revocation_reason: str | None = None
