# Generated by scripts/compile_schemas.py
# Do not edit manually — re-run the script to regenerate.

from __future__ import annotations


from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, confloat, conint, constr


class SecurityCeiling(Enum):
    public = 'public'
    internal = 'internal'
    confidential = 'confidential'
    restricted = 'restricted'


class Role(Enum):
    evidence = 'evidence'
    memory = 'memory'
    knowledge = 'knowledge'
    intelligence = 'intelligence'


class Item(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    object_id: str
    object_version: conint(ge=1)
    score: confloat(ge=0.0, le=1.0)
    role: Role
    source_refs: list[str]


class Status(Enum):
    open = 'open'
    resolved = 'resolved'
    accepted_tension = 'accepted_tension'


class Contradiction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    left_ref: str
    right_ref: str
    type: str
    status: Status


class Reason(Enum):
    access_denied = 'access_denied'
    stale = 'stale'
    budget = 'budget'
    low_relevance = 'low_relevance'
    invalid = 'invalid'
    unavailable = 'unavailable'


class Omission(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    reason: Reason
    count: conint(ge=1)


class Freshness(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    oldest_recorded_at: AwareDatetime
    newest_recorded_at: AwareDatetime


class AnimusContextEnvelope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    envelope_id: constr(pattern=r'^ce-[a-z0-9_-]+$')
    trace_id: constr(min_length=3)
    owner_id: constr(pattern=r'^owner-[a-z0-9_-]+$')
    workspace_id: constr(pattern=r'^ws-[a-z0-9_-]+$')
    purpose: constr(min_length=1)
    query: constr(min_length=1)
    as_of: AwareDatetime
    security_ceiling: SecurityCeiling
    token_budget: conint(ge=1)
    items: list[Item]
    contradictions: list[Contradiction]
    omissions: list[Omission]
    freshness: Freshness
    created_at: AwareDatetime
