# Generated by scripts/compile_schemas.py
# Do not edit manually — re-run the script to regenerate.

from __future__ import annotations


from enum import Enum
from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr

from .common import Common


class Authority(Enum):
    owner = 'owner'
    standing_policy = 'standing_policy'
    delegated = 'delegated'


class Payload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    question: constr(min_length=1)
    chosen_option: constr(min_length=1)
    alternatives: list[str] = Field(..., min_length=1)
    rationale: constr(min_length=1)
    authority: Authority
    decision_at: AwareDatetime
    review_trigger: str | None = None


class AnimusDecisionObject(Common):
    artifact_type: Literal['decision'] | None = None
    schema_id: Literal['https://animus.local/schemas/decision.schema.json'] | None = (
        None
    )
    payload: Payload | None = None
