# Generated by scripts/compile_schemas.py
# Do not edit manually — re-run the script to regenerate.

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, constr

from .common import Common


class EntityKind(Enum):
    person = "person"
    organization = "organization"
    place = "place"
    system = "system"
    concept = "concept"
    asset = "asset"
    document = "document"
    project = "project"
    other = "other"


class Payload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    entity_kind: EntityKind
    canonical_name: constr(min_length=1)
    aliases: list[str]
    attributes: dict[str, Any] | None = None
    external_ids: dict[str, str] | None = None


class AnimusEntityObject(Common):
    artifact_type: Literal["entity"] | None = None
    schema_id: Literal["https://animus.local/schemas/entity.schema.json"] | None = None
    payload: Payload | None = None
