# Generated by scripts/compile_schemas.py
# Do not edit manually — re-run the script to regenerate.

from __future__ import annotations

from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, constr

from .common import Common


class Payload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    event_kind: constr(min_length=1)
    occurred_at: AwareDatetime
    actor_refs: list[str]
    object_refs: list[str]
    event_data: dict[str, Any]
    idempotency_key: str | None = None


class AnimusEventObject(Common):
    artifact_type: Literal["event"] | None = None
    schema_id: Literal["https://animus.local/schemas/event.schema.json"] | None = None
    payload: Payload | None = None
