# Generated by scripts/compile_schemas.py
# Do not edit manually — re-run the script to regenerate.

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, confloat, constr

from .common import Common


class AlternativeOutcome(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    outcome: str
    probability: confloat(ge=0.0, le=1.0)


class Resolution(Enum):
    true = "true"
    false = "false"
    ambiguous = "ambiguous"
    cancelled = "cancelled"
    NoneType_None = None


class Payload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    statement: constr(min_length=1)
    probability: confloat(ge=0.0, le=1.0)
    horizon: AwareDatetime
    resolution_rule: constr(min_length=1)
    assumptions: list[str] = Field(..., min_length=1)
    alternative_outcomes: list[AlternativeOutcome] = Field(..., min_length=1)
    resolved_at: AwareDatetime | None = None
    resolution: Resolution | None = None
    brier_score: confloat(ge=0.0, le=1.0) | None = None


class AnimusForecastObject(Common):
    artifact_type: Literal["forecast"] | None = None
    schema_id: Literal["https://animus.local/schemas/forecast.schema.json"] | None = None
    payload: Payload | None = None
