# Generated by scripts/compile_schemas.py
# Do not edit manually — re-run the script to regenerate.

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, confloat, constr

from .common import Common


class Payload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    statement: constr(min_length=1)
    pattern_refs: list[str] = Field(..., min_length=1)
    predictions: list[str] = Field(..., min_length=1)
    falsification_conditions: list[str] = Field(..., min_length=1)
    alternatives: list[str] = Field(..., min_length=1)
    prior_probability: confloat(ge=0.0, le=1.0) | None = None


class AnimusHypothesisObject(Common):
    artifact_type: Literal["hypothesis"] | None = None
    schema_id: Literal["https://animus.local/schemas/hypothesis.schema.json"] | None = None
    payload: Payload | None = None
