# Generated by scripts/compile_schemas.py
# Do not edit manually — re-run the script to regenerate.

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, confloat, constr

from .common import Common


class Payload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    statement: constr(min_length=1)
    evidence_refs: list[str] = Field(..., min_length=1)
    scope: constr(min_length=1)
    confidence: confloat(ge=0.0, le=1.0)
    application_conditions: list[str] = Field(..., min_length=1)
    counterexamples: list[str] | None = None


class AnimusLessonObject(Common):
    artifact_type: Literal["lesson"] | None = None
    schema_id: Literal["https://animus.local/schemas/lesson.schema.json"] | None = None
    payload: Payload | None = None
