# Generated by scripts/compile_schemas.py
# Do not edit manually — re-run the script to regenerate.

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, constr


class Validation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source_valid: bool
    scope_valid: bool
    time_valid: bool
    sensitivity_valid: bool
    confidence_valid: bool


class Status(Enum):
    candidate = "candidate"
    approved = "approved"
    rejected = "rejected"
    committed = "committed"


class AnimusMemoryCandidate(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    candidate_id: constr(pattern=r"^mc-[a-z0-9_-]+$")
    owner_id: constr(pattern=r"^owner-[a-z0-9_-]+$")
    workspace_id: constr(pattern=r"^ws-[a-z0-9_-]+$")
    proposed_object: dict[str, Any]
    candidate_reason: constr(min_length=1)
    duplicate_refs: list[str]
    contradiction_refs: list[str]
    validation: Validation
    approval_required: bool
    approval_id: str | None = None
    status: Status
    created_at: AwareDatetime
    resolved_at: AwareDatetime | None = None
