# Generated by scripts/compile_schemas.py
# Do not edit manually — re-run the script to regenerate.

from __future__ import annotations


from enum import Enum
from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, constr

from .common import Common


class ObservationMethod(Enum):
    direct = 'direct'
    document_extraction = 'document_extraction'
    measurement = 'measurement'
    reported = 'reported'
    computed = 'computed'


class SourceAnchor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source_id: str
    locator: str


class Payload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: constr(min_length=1)
    observed_at: AwareDatetime
    observation_method: ObservationMethod
    source_anchor: SourceAnchor
    measurement: dict[str, Any] | None = None


class AnimusObservationObject(Common):
    artifact_type: Literal['observation'] | None = None
    schema_id: (
        Literal['https://animus.local/schemas/observation.schema.json'] | None
    ) = None
    payload: Payload | None = None
