# Generated by scripts/compile_schemas.py
# Do not edit manually — re-run the script to regenerate.

from __future__ import annotations

from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, conint, constr


class OutboxEntry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    entry_id: constr(pattern=r"^[a-z]+-[a-z0-9_-]+$")
    topic: constr(min_length=1)
    payload: dict[str, Any]
    headers: dict[str, str]
    created_at: AwareDatetime
    claimed_at: AwareDatetime | None = None
    claimed_by: str | None = None
    retry_count: conint(ge=0) | None = 0
    processed_at: AwareDatetime | None = None
    error_message: str | None = None
