# Generated by scripts/compile_schemas.py
# Do not edit manually — re-run the script to regenerate.

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, constr

from .common import Common


class ExpectedComparison(Enum):
    better = "better"
    as_expected = "as_expected"
    worse = "worse"
    inconclusive = "inconclusive"


class Payload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    action_refs: list[str] = Field(..., min_length=1)
    description: constr(min_length=1)
    observed_at: AwareDatetime
    metrics: dict[str, Any]
    expected_comparison: ExpectedComparison


class AnimusOutcomeObject(Common):
    artifact_type: Literal["outcome"] | None = None
    schema_id: Literal["https://animus.local/schemas/outcome.schema.json"] | None = None
    payload: Payload | None = None
