# Generated by scripts/compile_schemas.py
# Do not edit manually — re-run the script to regenerate.

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, confloat, conint, constr

from .common import Common


class Payload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    description: constr(min_length=1)
    signal_refs: list[str] = Field(..., min_length=2)
    support_count: conint(ge=2)
    independence_score: confloat(ge=0.0, le=1.0)
    method: constr(min_length=1)
    counterexamples: list[str] | None = None


class AnimusPatternObject(Common):
    artifact_type: Literal["pattern"] | None = None
    schema_id: Literal["https://animus.local/schemas/pattern.schema.json"] | None = None
    payload: Payload | None = None
