# Generated by scripts/compile_schemas.py
# Do not edit manually — re-run the script to regenerate.

from __future__ import annotations

from enum import Enum

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, confloat, constr


class Action(Enum):
    create = "create"
    read = "read"
    update = "update"
    delete = "delete"
    execute = "execute"
    approve = "approve"
    delegate = "delegate"
    export = "export"
    import_ = "import"


class InputContext(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    action: Action
    resource: constr(min_length=1)
    principal: constr(min_length=3)
    workspace_id: constr(pattern=r"^ws-[a-z0-9_-]+$") | None = None
    schema_id: str | None = None
    payload_summary: str | None = None


class Decision(Enum):
    allow = "allow"
    deny = "deny"
    abstain = "abstain"
    escalate = "escalate"


class DenialReasonCode(Enum):
    missing_scope = "missing_scope"
    stale_approval = "stale_approval"
    unknown_schema = "unknown_schema"
    invalid_transition = "invalid_transition"
    budget_exhausted = "budget_exhausted"
    capability_revoked = "capability_revoked"
    policy_conflict = "policy_conflict"
    escalation_required = "escalation_required"
    NoneType_None = None


class ObligationType(Enum):
    log = "log"
    notify = "notify"
    approve = "approve"
    audit = "audit"
    rate_limit = "rate_limit"


class Obligation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    obligation_type: ObligationType
    description: constr(min_length=1)
    target: str | None = None
    deadline: AwareDatetime | None = None


class PolicyDecision(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    decision_id: constr(pattern=r"^dec-[a-z0-9_-]+$")
    rule_id: constr(min_length=1) = Field(
        ..., description="Identifier of the policy rule that triggered this decision"
    )
    input_context: InputContext
    decision: Decision
    confidence: confloat(ge=0.0, le=1.0) | None = None
    reason: constr(min_length=1) | None = None
    denial_reason_code: DenialReasonCode | None = None
    obligations: list[Obligation] | None = None
    principal: constr(min_length=3)
    workspace_id: constr(pattern=r"^ws-[a-z0-9_-]+$")
    tx_time: AwareDatetime
    parent_decision_id: constr(pattern=r"^dec-[a-z0-9_-]+$") | None = None
