# Generated by scripts/compile_schemas.py
# Do not edit manually — re-run the script to regenerate.

from __future__ import annotations


from enum import Enum
from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, confloat, constr

from .common import Common


class Payload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    description: constr(min_length=1)
    observation_refs: list[str] = Field(..., min_length=1)
    relevance: confloat(ge=0.0, le=1.0)
    novelty: confloat(ge=0.0, le=1.0)
    expiry_at: AwareDatetime | None = None


class AnimusSignalObject(Common):
    artifact_type: Literal['signal'] | None = None
    schema_id: Literal['https://animus.local/schemas/signal.schema.json'] | None = None
    payload: Payload | None = None
