# Generated by scripts/compile_schemas.py
# Do not edit manually — re-run the script to regenerate.

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, constr


class Status(Enum):
    running = "running"
    succeeded = "succeeded"
    failed = "failed"
    cancelled = "cancelled"
    degraded = "degraded"


class Kind(Enum):
    retrieval = "retrieval"
    model = "model"
    tool = "tool"
    policy = "policy"
    write = "write"
    queue = "queue"
    evaluation = "evaluation"
    view = "view"


class Status6(Enum):
    running = "running"
    succeeded = "succeeded"
    failed = "failed"
    denied = "denied"
    cancelled = "cancelled"


class Span(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    span_id: str
    parent_span_id: str | None = None
    kind: Kind
    started_at: AwareDatetime
    completed_at: AwareDatetime | None = None
    status: Status6
    input_hash: str | None = None
    output_hash: str | None = None
    metadata: dict[str, Any] | None = None


class ReplayStatus(Enum):
    not_tested = "not_tested"
    passed = "passed"
    failed = "failed"
    not_reproducible = "not_reproducible"


class Reproducibility(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    captured_inputs: bool
    captured_prompts: bool
    captured_model_ids: bool
    captured_tool_versions: bool
    replay_status: ReplayStatus


class AnimusTraceBundle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trace_id: constr(pattern=r"^tr-[a-z0-9_-]+$")
    owner_id: constr(pattern=r"^owner-[a-z0-9_-]+$")
    workspace_id: constr(pattern=r"^ws-[a-z0-9_-]+$")
    purpose: constr(min_length=1)
    started_at: AwareDatetime
    completed_at: AwareDatetime | None
    status: Status
    spans: list[Span]
    input_hashes: list[constr(pattern=r"^[a-f0-9]{64}$")]
    output_hashes: list[constr(pattern=r"^[a-f0-9]{64}$")]
    policy_versions: list[str]
    schema_versions: list[str]
    reproducibility: Reproducibility
