"""Protocol for sync clients."""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol, runtime_checkable

from animus.sync.state import StateDelta


@runtime_checkable
class SyncProvider(Protocol):
    """Structural interface for device sync clients."""

    @property
    def is_connected(self) -> bool: ...

    def add_delta_callback(self, callback: Callable[[StateDelta], None]) -> None: ...
    async def connect(self, address: str) -> bool: ...
    async def disconnect(self) -> None: ...
    async def sync(self) -> Any: ...
    async def push_changes(self, delta: StateDelta) -> bool: ...
    async def ping(self) -> int | None: ...
    async def listen(self) -> None: ...
