# Generated by scripts/compile_schemas.py
# Do not edit manually — re-run the script to regenerate.

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, confloat, constr

from .common import Common


class ClaimKind(Enum):
    factual = "factual"
    causal = "causal"
    interpretive = "interpretive"
    normative = "normative"
    identity = "identity"
    requirement = "requirement"


class Payload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    proposition: constr(min_length=1)
    claim_kind: ClaimKind
    supporting_evidence: list[str] = Field(..., min_length=1)
    contradicting_evidence: list[str]
    confidence: confloat(ge=0.0, le=1.0)
    contradiction_refs: list[str] | None = None


class AnimusClaimObject(Common):
    artifact_type: Literal["claim"] | None = None
    schema_id: Literal["https://animus.local/schemas/claim.schema.json"] | None = None
    payload: Payload | None = None
