#!/usr/bin/env python3
"""
compile_schemas.py — Generate Python Pydantic models from JSON Schema contracts.

Usage:
    python scripts/compile_schemas.py

Reads packages/contracts/*.schema.json and writes generated Pydantic v2 models
into packages/types/src/animus_types/.

Requires:
    - datamodel-code-generator (pip install datamodel-code-generator)
    - Pydantic v2 (already in the environment)

Generated code is committed so CI can validate against it.
"""
from __future__ import annotations

import glob
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.resolve()
CONTRACTS_DIR = REPO_ROOT / "packages" / "contracts"
TYPES_DIR = REPO_ROOT / "packages" / "types" / "src" / "animus_types"


def run(cmd: list[str], cwd: Path | None = None) -> None:
    proc = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if proc.returncode != 0:
        print(f"ERROR running {' '.join(cmd)}:\n{proc.stderr}", file=sys.stderr)
        sys.exit(1)


def snake_case(name: str) -> str:
    """Convert CamelCase or kebab-case to snake_case."""
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    s = re.sub(r"([a-z\d])([A-Z])", r"\1_\2", s)
    return s.lower().replace("-", "_")


def extract_class_names(source: str) -> set[str]:
    """Extract top-level class definitions from Python source."""
    return {m.group(1) for m in re.finditer(r"^class\s+(\w+)", source, re.MULTILINE)}


def extract_imported_names(source: str) -> set[str]:
    """Extract names imported via 'from .common import X, Y'."""
    names: set[str] = set()
    for line in source.splitlines():
        m = re.match(r"from\s+\.common\s+import\s+(.+)", line)
        if m:
            for part in m.group(1).split(","):
                names.add(part.strip())
    return names


def generate() -> None:
    schemas = sorted(CONTRACTS_DIR.glob("*.schema.json"))
    if not schemas:
        print(f"ERROR: No .schema.json files found in {CONTRACTS_DIR}", file=sys.stderr)
        sys.exit(1)

    # --- Step 1: Generate with datamodel-codegen to temp dir ----------------
    with tempfile.TemporaryDirectory() as tmpdir:
        input_dir = Path(tmpdir) / "input"
        input_dir.mkdir()
        for s in schemas:
            shutil.copy(s, input_dir / s.name)

        output_dir = Path(tmpdir) / "output"
        output_dir.mkdir()

        run([
            "datamodel-codegen",
            "--input", str(input_dir),
            "--input-file-type", "jsonschema",
            "--output", str(output_dir),
            "--use-union-operator",
            "--target-python-version", "3.12",
            "--output-model-type", "pydantic_v2.BaseModel",
        ])

        # --- Step 2: Post-process ------------------------------------------
        generated = {p.stem: p.read_text(encoding="utf-8") for p in output_dir.glob("*.py")}
        common_source = generated.pop("common_schema", "")
        if not common_source:
            print("ERROR: common_schema.py not generated", file=sys.stderr)
            sys.exit(1)

        common_classes = extract_class_names(common_source)
        # Keep only the BaseModel subclasses; drop module-level imports
        common_model_classes = {
            cls for cls in common_classes
            if cls not in {"Enum", "BaseModel", "ConfigDict", "RootModel",
                           "AwareDatetime", "conint", "constr", "Any", "Literal"}
        }

        # Rename base class globally before processing individual files
        for stem in list(generated.keys()):
            generated[stem] = generated[stem].replace(
                "AnimusCanonicalObjectEnvelope", "Common"
            )
        common_source = common_source.replace("AnimusCanonicalObjectEnvelope", "Common")

        # Build clean common.py (strip datamodel-codegen header for our own)
        common_py = (
            '# Generated by scripts/compile_schemas.py\n'
            '# Do not edit manually — re-run the script to regenerate.\n\n'
            'from __future__ import annotations\n\n'
        )
        # Append original common source minus its header
        common_lines = common_source.splitlines()
        header_end = 0
        for i, line in enumerate(common_lines):
            if line.startswith("from __future__"):
                header_end = i + 1
                break
        common_py += "\n".join(common_lines[header_end:]) + "\n"

        # Prepare output map: module_name -> source
        outputs: dict[str, str] = {}
        outputs["common"] = common_py

        for stem, source in generated.items():
            # Strip _schema suffix from module name
            module = stem.replace("_schema", "")

            # Remove duplicate class definitions that exist in common
            lines = source.splitlines()
            cleaned_lines: list[str] = []
            skip_until_dedent = False
            indent_level = 0

            for line in lines:
                # Detect class definition line
                class_match = re.match(r"^(class\s+(\w+)\(.*\):)", line)
                if class_match:
                    class_name = class_match.group(2)
                    if class_name in common_model_classes:
                        skip_until_dedent = True
                        indent_level = len(line) - len(line.lstrip())
                        continue
                    else:
                        skip_until_dedent = False

                if skip_until_dedent:
                    if line.strip() == "":
                        continue
                    current_indent = len(line) - len(line.lstrip())
                    if current_indent <= indent_level and line.strip():
                        skip_until_dedent = False
                    else:
                        continue

                cleaned_lines.append(line)

            cleaned = "\n".join(cleaned_lines)

            # Fix imports: replace 'from .common_schema import X' with 'from .common import X'
            cleaned = cleaned.replace("from .common_schema import", "from .common import")

            # Clean header
            header_end = 0
            for i, line in enumerate(cleaned.splitlines()):
                if line.startswith("from __future__"):
                    header_end = i + 1
                    break

            final_source = (
                '# Generated by scripts/compile_schemas.py\n'
                '# Do not edit manually — re-run the script to regenerate.\n\n'
                'from __future__ import annotations\n\n'
                + "\n".join(cleaned.splitlines()[header_end:])
                + "\n"
            )

            outputs[module] = final_source

        # --- Step 3: Write to packages/types/src/animus_types/ -----------
        # Back up old files
        backup_dir = TYPES_DIR / "_legacy"
        if backup_dir.exists():
            shutil.rmtree(backup_dir)
        backup_dir.mkdir()

        for existing in TYPES_DIR.glob("*.py"):
            if existing.name != "__init__.py":
                shutil.copy(existing, backup_dir / existing.name)

        # Write new modules
        for module, source in outputs.items():
            out_path = TYPES_DIR / f"{module}.py"
            out_path.write_text(source, encoding="utf-8")
            print(f"  Wrote {out_path.relative_to(REPO_ROOT)}")

        # --- Step 4: Generate __init__.py ----------------------------------
        init_lines = [
            '# Generated by scripts/compile_schemas.py',
            '# Do not edit manually — re-run the script to regenerate.',
            '',
            'from __future__ import annotations',
            '',
            '# Re-export legacy types (preserved for backward compatibility)',
            'from animus_types.egress import EgressDeniedError, is_egress_allowed',
            'from animus_types.sensitivity import Sensitivity',
            '',
            '# Generated contract models',
            'from animus_types.common import (',
            '    Common,',
            '    SubjectDomain,',
            '    ArtifactType,',
            '    CognitiveRole,',
            '    WorkflowStatus,',
            '    EpistemicStatus,',
            '    LifecycleStatus,',
            '    StorageTier,',
            '    Presentation,',
            '    SecurityClass,',
            '    ValidTime,',
            '    TransactionTime,',
            '    Provenance,',
            '    Integrity,',
            '    Tag,',
            ')',
            '',
        ]

        # Import each schema module's main class
        for module in sorted(outputs.keys()):
            if module == "common":
                continue
            source = outputs[module]
            for match in re.finditer(r"^class\s+(\w+)\(Common\):", source, re.MULTILINE):
                cls_name = match.group(1)
                init_lines.append(f"from animus_types.{module} import {cls_name}")
                break

        init_lines.extend([
            '',
            '__all__ = [',
            '    # Legacy',
            '    "EgressDeniedError",',
            '    "is_egress_allowed",',
            '    "Sensitivity",',
            '    # Common',
            '    "Common",',
            '    "SubjectDomain",',
            '    "ArtifactType",',
            '    "CognitiveRole",',
            '    "WorkflowStatus",',
            '    "EpistemicStatus",',
            '    "LifecycleStatus",',
            '    "StorageTier",',
            '    "Presentation",',
            '    "SecurityClass",',
            '    "ValidTime",',
            '    "TransactionTime",',
            '    "Provenance",',
            '    "Integrity",',
            '    "Tag",',
            '    # Schema models',
        ])

        for module in sorted(outputs.keys()):
            if module == "common":
                continue
            source = outputs[module]
            for match in re.finditer(r"^class\s+(\w+)\(Common\):", source, re.MULTILINE):
                cls_name = match.group(1)
                init_lines.append(f'    "{cls_name}",')
                break

        init_lines.extend([
            ']',
            '',
        ])

        init_path = TYPES_DIR / "__init__.py"
        init_path.write_text("\n".join(init_lines) + "\n", encoding="utf-8")
        print(f"  Wrote {init_path.relative_to(REPO_ROOT)}")

    print(f"\nDone. Generated {len(outputs)} modules in {TYPES_DIR.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    generate()
