/** Token storage for remote-access auth.
 *
 * A single shared bearer token (generated by the backend on first remote run)
 * is stored in localStorage and sent with every REST request and on the chat
 * WebSocket handshake.
 */

const TOKEN_KEY = "animus_token";

export function getToken(): string | null {
  return localStorage.getItem(TOKEN_KEY);
}

export function setToken(token: string): void {
  localStorage.setItem(TOKEN_KEY, token);
}

export function clearToken(): void {
  localStorage.removeItem(TOKEN_KEY);
}

/** Raised when the backend rejects the stored token (HTTP 401). */
export class AuthError extends Error {
  constructor(message = "Authentication required") {
    super(message);
    this.name = "AuthError";
  }
}
